name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Buildroot dependencies
        run: |
          apt install build-essential gcc g++ cpio rsync wget libncurses-dev

      - name: Git clone Buildroot
        run: git clone https://github.com/buildroot/buildroot